export const citiesData: Record<string, Record<string, string[]>> = {
  IN: {
    "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool", "Tirupati", "Rajahmundry", "Kadapa", "Kakinada", "Anantapur", "Eluru", "Ongole", "Nandyal", "Machilipatnam", "Chittoor"],
    "Arunachal Pradesh": ["Itanagar", "Naharlagun", "Pasighat", "Tawang", "Ziro", "Bomdila", "Tezu", "Roing"],
    "Assam": ["Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Nagaon", "Tinsukia", "Tezpur", "Bongaigaon", "Dhubri", "North Lakhimpur"],
    "Bihar": ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Purnia", "Darbhanga", "Bihar Sharif", "Arrah", "Begusarai", "Katihar", "Munger", "Chhapra", "Hajipur", "Sasaram"],
    "Chhattisgarh": ["Raipur", "Bhilai", "Bilaspur", "Korba", "Durg", "Rajnandgaon", "Raigarh", "Jagdalpur", "Ambikapur"],
    "Goa": ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda", "Bicholim"],
    "Gujarat": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar", "Junagadh", "Gandhinagar", "Anand", "Bharuch", "Morbi", "Mehsana", "Nadiad", "Navsari", "Porbandar", "Vapi", "Gandhidham"],
    "Haryana": ["Faridabad", "Gurgaon", "Panipat", "Ambala", "Yamunanagar", "Rohtak", "Hisar", "Karnal", "Sonipat", "Panchkula", "Bhiwani", "Sirsa", "Bahadurgarh", "Jind", "Thanesar", "Kaithal"],
    "Himachal Pradesh": ["Shimla", "Mandi", "Dharamshala", "Solan", "Nahan", "Bilaspur", "Chamba", "Hamirpur", "Una", "Palampur", "Kullu", "Manali"],
    "Jharkhand": ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Deoghar", "Hazaribagh", "Giridih", "Ramgarh", "Phusro", "Medininagar"],
    "Karnataka": ["Bangalore", "Mysore", "Hubli", "Mangalore", "Belgaum", "Gulbarga", "Davanagere", "Bellary", "Shimoga", "Tumkur", "Bijapur", "Raichur", "Bidar", "Hospet", "Hassan", "Chitradurga", "Udupi", "Mandya"],
    "Kerala": ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam", "Palakkad", "Alappuzha", "Kannur", "Kottayam", "Malappuram", "Kasaragod", "Pathanamthitta", "Idukki", "Wayanad"],
    "Madhya Pradesh": ["Indore", "Bhopal", "Jabalpur", "Gwalior", "Ujjain", "Sagar", "Dewas", "Satna", "Ratlam", "Rewa", "Murwara", "Singrauli", "Burhanpur", "Khandwa", "Bhind", "Chhindwara", "Guna", "Shivpuri"],
    "Maharashtra": ["Mumbai", "Pune", "Nagpur", "Thane", "Nashik", "Aurangabad", "Solapur", "Kolhapur", "Amravati", "Navi Mumbai", "Sangli", "Jalgaon", "Akola", "Latur", "Dhule", "Ahmednagar", "Chandrapur", "Parbhani", "Ichalkaranji", "Jalna", "Bhiwandi"],
    "Manipur": ["Imphal", "Thoubal", "Bishnupur", "Churachandpur", "Kakching", "Senapati"],
    "Meghalaya": ["Shillong", "Tura", "Nongstoin", "Jowai", "Baghmara", "Williamnagar"],
    "Mizoram": ["Aizawl", "Lunglei", "Champhai", "Serchhip", "Kolasib", "Lawngtlai"],
    "Nagaland": ["Kohima", "Dimapur", "Mokokchung", "Tuensang", "Wokha", "Zunheboto"],
    "Odisha": ["Bhubaneswar", "Cuttack", "Rourkela", "Berhampur", "Sambalpur", "Puri", "Balasore", "Bhadrak", "Baripada", "Jharsuguda", "Jeypore", "Bargarh", "Paradip", "Angul"],
    "Punjab": ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Pathankot", "Mohali", "Hoshiarpur", "Batala", "Moga", "Malerkotla", "Khanna", "Phagwara", "Muktsar", "Barnala", "Rajpura", "Firozpur", "Kapurthala"],
    "Rajasthan": ["Jaipur", "Jodhpur", "Kota", "Bikaner", "Ajmer", "Udaipur", "Bhilwara", "Alwar", "Bharatpur", "Sikar", "Pali", "Sri Ganganagar", "Tonk", "Beawar", "Hanumangarh", "Kishangarh", "Nagaur", "Makrana", "Churu", "Baran", "Dholpur", "Jhunjhunu", "Chittorgarh", "Barmer"],
    "Sikkim": ["Gangtok", "Namchi", "Mangan", "Gyalshing", "Rangpo", "Singtam", "Jorethang"],
    "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tiruppur", "Erode", "Vellore", "Thoothukudi", "Tirunelveli", "Nagercoil", "Thanjavur", "Dindigul", "Cuddalore", "Kanchipuram", "Karur", "Hosur", "Kumbakonam", "Rajapalayam", "Pudukkottai", "Pollachi"],
    "Telangana": ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Ramagundam", "Khammam", "Mahbubnagar", "Nalgonda", "Adilabad", "Suryapet", "Miryalaguda", "Siddipet", "Mancherial"],
    "Tripura": ["Agartala", "Dharmanagar", "Udaipur", "Kailashahar", "Belonia", "Ambassa", "Khowai", "Sabroom"],
    "Uttar Pradesh": ["Lucknow", "Kanpur", "Ghaziabad", "Agra", "Varanasi", "Meerut", "Allahabad", "Bareilly", "Aligarh", "Moradabad", "Saharanpur", "Gorakhpur", "Noida", "Firozabad", "Jhansi", "Muzaffarnagar", "Mathura", "Rampur", "Shahjahanpur", "Farrukhabad", "Mau", "Hapur", "Etawah", "Mirzapur", "Bulandshahr", "Sambhal", "Amroha", "Hardoi", "Fatehpur", "Raebareli", "Orai", "Sitapur", "Bahraich", "Modinagar", "Unnao", "Jaunpur", "Lakhimpur", "Hathras", "Banda", "Pilibhit", "Barabanki", "Khurja", "Gonda", "Mainpuri", "Lalitpur", "Etah", "Deoria", "Ujhani", "Sultanpur", "Azamgarh", "Bijnor", "Sahaswan", "Basti", "Chandausi", "Akbarpur", "Ballia", "Tanda", "Greater Noida"],
    "Uttarakhand": ["Dehradun", "Haridwar", "Roorkee", "Haldwani", "Rudrapur", "Kashipur", "Rishikesh", "Pithoragarh", "Ramnagar", "Almora", "Mussoorie", "Nainital"],
    "West Bengal": ["Kolkata", "Asansol", "Siliguri", "Durgapur", "Bardhaman", "Malda", "Baharampur", "Habra", "Kharagpur", "Shantipur", "Dankuni", "Dhulian", "Ranaghat", "Haldia", "Raiganj", "Krishnanagar", "Nabadwip", "Medinipur", "Jalpaiguri", "Balurghat", "Basirhat", "Bankura", "Chakdaha", "Darjeeling"],
    "Andaman and Nicobar Islands": ["Port Blair", "Diglipur", "Rangat", "Mayabunder", "Car Nicobar"],
    "Chandigarh": ["Chandigarh"],
    "Dadra and Nagar Haveli and Daman and Diu": ["Daman", "Diu", "Silvassa"],
    "Delhi": ["New Delhi", "Delhi", "Dwarka", "Rohini", "Pitampura", "Janakpuri", "Laxmi Nagar", "Saket", "Vasant Kunj", "Mayur Vihar", "Karol Bagh"],
    "Jammu and Kashmir": ["Srinagar", "Jammu", "Anantnag", "Baramulla", "Sopore", "Kathua", "Udhampur", "Pulwama", "Kupwara", "Rajouri"],
    "Ladakh": ["Leh", "Kargil"],
    "Lakshadweep": ["Kavaratti", "Agatti", "Minicoy", "Amini"],
    "Puducherry": ["Puducherry", "Karaikal", "Yanam", "Mahe"],
  },
  US: {
    "Alabama": ["Birmingham", "Montgomery", "Huntsville", "Mobile", "Tuscaloosa", "Hoover", "Dothan", "Auburn", "Decatur", "Madison"],
    "Alaska": ["Anchorage", "Fairbanks", "Juneau", "Sitka", "Ketchikan", "Wasilla", "Kenai", "Kodiak", "Bethel", "Palmer"],
    "Arizona": ["Phoenix", "Tucson", "Mesa", "Chandler", "Scottsdale", "Glendale", "Gilbert", "Tempe", "Peoria", "Surprise", "Yuma", "Flagstaff"],
    "Arkansas": ["Little Rock", "Fort Smith", "Fayetteville", "Springdale", "Jonesboro", "Rogers", "Conway", "North Little Rock", "Bentonville"],
    "California": ["Los Angeles", "San Diego", "San Jose", "San Francisco", "Fresno", "Sacramento", "Long Beach", "Oakland", "Bakersfield", "Anaheim", "Santa Ana", "Riverside", "Stockton", "Irvine", "Chula Vista", "Fremont", "San Bernardino", "Modesto", "Moreno Valley", "Fontana", "Glendale", "Huntington Beach", "Santa Clarita", "Garden Grove", "Oceanside", "Rancho Cucamonga", "Santa Rosa", "Ontario", "Elk Grove", "Corona", "Lancaster", "Palmdale", "Salinas", "Pomona", "Hayward", "Escondido", "Sunnyvale", "Torrance", "Pasadena", "Orange", "Fullerton", "Thousand Oaks", "Roseville", "Concord", "Simi Valley", "Santa Clara", "Victorville", "Vallejo", "Berkeley", "El Monte", "Downey", "Costa Mesa", "Inglewood", "Carlsbad", "San Buenaventura", "Fairfield", "West Covina", "Murrieta", "Richmond", "Norwalk", "Antioch", "Temecula", "Burbank", "Daly City", "Rialto", "El Cajon", "San Mateo", "Clovis", "Compton", "Jurupa Valley", "Vista", "South Gate", "Mission Viejo", "Vacaville", "Carson", "Hesperia", "Santa Maria", "Redding", "Westminster", "Santa Monica", "Chico", "Newport Beach", "San Leandro", "San Marcos", "Whittier", "Hawthorne", "Citrus Heights", "Alhambra", "Tracy", "Livermore", "Buena Park", "Menifee", "Hemet", "Lakewood", "Merced", "Chino", "Indio", "Redwood City", "Lake Forest", "Napa", "Tustin", "Bellflower", "Mountain View", "Chino Hills", "Baldwin Park", "Alameda", "Upland", "San Ramon", "Folsom", "Pleasanton", "Lynwood", "Union City", "Apple Valley", "Redlands", "Turlock"],
    "Colorado": ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Lakewood", "Thornton", "Arvada", "Westminster", "Pueblo", "Centennial", "Boulder", "Greeley", "Longmont"],
    "Connecticut": ["Bridgeport", "New Haven", "Stamford", "Hartford", "Waterbury", "Norwalk", "Danbury", "New Britain", "Bristol", "Meriden", "West Haven", "Milford"],
    "Delaware": ["Wilmington", "Dover", "Newark", "Middletown", "Smyrna", "Milford", "Seaford", "Georgetown"],
    "Florida": ["Jacksonville", "Miami", "Tampa", "Orlando", "St. Petersburg", "Hialeah", "Tallahassee", "Fort Lauderdale", "Port St. Lucie", "Cape Coral", "Pembroke Pines", "Hollywood", "Miramar", "Gainesville", "Coral Springs", "Miami Gardens", "Clearwater", "Palm Bay", "Pompano Beach", "West Palm Beach", "Lakeland", "Davie", "Miami Beach", "Sunrise", "Boca Raton", "Deltona", "Plantation", "Fort Myers", "Deerfield Beach", "Palm Coast"],
    "Georgia": ["Atlanta", "Augusta", "Columbus", "Macon", "Savannah", "Athens", "Sandy Springs", "South Fulton", "Roswell", "Johns Creek", "Warner Robins", "Albany", "Alpharetta", "Marietta", "Stonecrest", "Smyrna"],
    "Hawaii": ["Honolulu", "East Honolulu", "Pearl City", "Hilo", "Kailua", "Waipahu", "Kaneohe", "Mililani", "Kahului", "Ewa Gentry"],
    "Idaho": ["Boise", "Meridian", "Nampa", "Idaho Falls", "Caldwell", "Pocatello", "Coeur d'Alene", "Twin Falls", "Lewiston"],
    "Illinois": ["Chicago", "Aurora", "Joliet", "Naperville", "Rockford", "Elgin", "Springfield", "Peoria", "Champaign", "Waukegan", "Cicero", "Bloomington", "Arlington Heights", "Evanston", "Decatur", "Schaumburg"],
    "Indiana": ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Carmel", "Fishers", "Bloomington", "Hammond", "Gary", "Lafayette", "Muncie", "Terre Haute"],
    "Iowa": ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Iowa City", "Waterloo", "Ames", "West Des Moines", "Council Bluffs", "Ankeny", "Dubuque", "Urbandale"],
    "Kansas": ["Wichita", "Overland Park", "Kansas City", "Olathe", "Topeka", "Lawrence", "Shawnee", "Manhattan", "Lenexa", "Salina", "Hutchinson"],
    "Kentucky": ["Louisville", "Lexington", "Bowling Green", "Owensboro", "Covington", "Richmond", "Georgetown", "Florence", "Hopkinsville", "Nicholasville", "Elizabethtown"],
    "Louisiana": ["New Orleans", "Baton Rouge", "Shreveport", "Metairie", "Lafayette", "Lake Charles", "Kenner", "Bossier City", "Monroe", "Alexandria", "Houma"],
    "Maine": ["Portland", "Lewiston", "Bangor", "South Portland", "Auburn", "Biddeford", "Sanford", "Brunswick", "Augusta", "Saco"],
    "Maryland": ["Baltimore", "Columbia", "Germantown", "Silver Spring", "Waldorf", "Frederick", "Ellicott City", "Glen Burnie", "Bethesda", "Dundalk", "Rockville", "Gaithersburg", "Bowie", "Annapolis"],
    "Massachusetts": ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell", "Brockton", "New Bedford", "Quincy", "Lynn", "Fall River", "Newton", "Lawrence", "Somerville", "Framingham", "Haverhill", "Waltham"],
    "Michigan": ["Detroit", "Grand Rapids", "Warren", "Sterling Heights", "Ann Arbor", "Lansing", "Flint", "Dearborn", "Livonia", "Clinton Township", "Canton", "Troy", "Farmington Hills", "Kalamazoo", "Wyoming", "Southfield", "Westland", "Rochester Hills", "Taylor", "Pontiac"],
    "Minnesota": ["Minneapolis", "Saint Paul", "Rochester", "Bloomington", "Duluth", "Brooklyn Park", "Plymouth", "Woodbury", "Maple Grove", "St. Cloud", "Eagan", "Eden Prairie", "Coon Rapids", "Burnsville", "Blaine", "Lakeville", "Minnetonka"],
    "Mississippi": ["Jackson", "Gulfport", "Southaven", "Hattiesburg", "Biloxi", "Meridian", "Olive Branch", "Tupelo", "Greenville", "Horn Lake"],
    "Missouri": ["Kansas City", "St. Louis", "Springfield", "Independence", "Columbia", "Lee's Summit", "O'Fallon", "St. Joseph", "St. Charles", "St. Peters", "Blue Springs", "Florissant", "Joplin", "Chesterfield"],
    "Montana": ["Billings", "Missoula", "Great Falls", "Bozeman", "Butte", "Helena", "Kalispell", "Havre", "Anaconda"],
    "Nebraska": ["Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney", "Fremont", "Hastings", "Norfolk", "North Platte"],
    "Nevada": ["Las Vegas", "Henderson", "Reno", "North Las Vegas", "Sparks", "Carson City", "Fernley", "Elko", "Mesquite", "Boulder City"],
    "New Hampshire": ["Manchester", "Nashua", "Concord", "Derry", "Dover", "Rochester", "Salem", "Merrimack", "Hudson", "Londonderry"],
    "New Jersey": ["Newark", "Jersey City", "Paterson", "Elizabeth", "Edison", "Woodbridge", "Lakewood", "Toms River", "Hamilton", "Trenton", "Clifton", "Camden", "Brick Township", "Cherry Hill", "Passaic", "Union City", "Old Bridge", "Middletown", "Gloucester Township", "East Orange", "Bayonne", "Franklin Township", "North Bergen", "Vineland", "Union Township", "Piscataway", "New Brunswick", "Jackson", "Wayne", "Irvington", "Parsippany-Troy Hills", "Hoboken", "Perth Amboy", "West New York", "Plainfield", "Bloomfield", "East Brunswick", "Washington Township", "West Orange", "South Brunswick", "Evesham Township", "Monroe Township", "Bridgewater Township", "Hackensack", "Sayreville", "Manchester Township", "Egg Harbor Township", "Linden", "Berkeley Township", "Manalapan Township", "North Brunswick Township", "Kearny", "Marlboro Township", "Atlantic City", "Winslow Township", "Montclair", "Galloway Township", "Freehold Township", "Mount Laurel", "Belleville", "Pemberton Township", "Howell Township", "Teaneck", "Fair Lawn", "Willingboro Township", "Long Branch", "Deptford Township", "Garfield", "Westfield", "City of Orange Township", "Millville", "Nutley", "Bergenfield", "Ewing Township", "Ocean Township"],
    "New Mexico": ["Albuquerque", "Las Cruces", "Rio Rancho", "Santa Fe", "Roswell", "Farmington", "Clovis", "Hobbs", "Alamogordo", "Carlsbad"],
    "New York": ["New York City", "Buffalo", "Rochester", "Yonkers", "Syracuse", "Albany", "New Rochelle", "Mount Vernon", "Schenectady", "Utica", "White Plains", "Troy", "Niagara Falls", "Binghamton", "Freeport", "Long Beach", "Ithaca", "Rome", "Poughkeepsie", "Jamestown", "Elmira", "Saratoga Springs", "North Tonawanda", "Newburgh", "Watertown"],
    "North Carolina": ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem", "Fayetteville", "Cary", "Wilmington", "High Point", "Concord", "Greenville", "Asheville", "Gastonia", "Jacksonville", "Chapel Hill", "Huntersville", "Burlington", "Rocky Mount", "Kannapolis", "Wilson", "Hickory", "Wake Forest", "Apex", "Indian Trail", "Mooresville", "Goldsboro", "Cornelius", "Monroe", "Salisbury", "Matthews", "Sanford"],
    "North Dakota": ["Fargo", "Bismarck", "Grand Forks", "Minot", "West Fargo", "Williston", "Dickinson", "Mandan", "Jamestown", "Wahpeton"],
    "Ohio": ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron", "Dayton", "Parma", "Canton", "Youngstown", "Lorain", "Hamilton", "Springfield", "Kettering", "Elyria", "Lakewood", "Cuyahoga Falls", "Middletown", "Euclid", "Newark", "Mansfield", "Mentor", "Cleveland Heights", "Beavercreek", "Strongsville", "Fairfield", "Dublin", "Warren", "Findlay", "Lancaster", "Lima", "Huber Heights", "Marion", "Westerville", "Grove City", "Reynoldsburg", "Delaware", "Brunswick", "Stow", "North Olmsted", "Gahanna"],
    "Oklahoma": ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Edmond", "Lawton", "Moore", "Midwest City", "Enid", "Stillwater", "Muskogee", "Bartlesville"],
    "Oregon": ["Portland", "Salem", "Eugene", "Gresham", "Hillsboro", "Beaverton", "Bend", "Medford", "Springfield", "Corvallis", "Albany", "Tigard", "Lake Oswego", "Keizer"],
    "Pennsylvania": ["Philadelphia", "Pittsburgh", "Allentown", "Reading", "Erie", "Scranton", "Bethlehem", "Lancaster", "Harrisburg", "Altoona", "York", "Wilkes-Barre", "Chester", "Williamsport", "Easton", "Lebanon", "Hazleton", "New Castle", "Johnstown", "McKeesport"],
    "Rhode Island": ["Providence", "Warwick", "Cranston", "Pawtucket", "East Providence", "Woonsocket", "Coventry", "Cumberland", "North Providence", "South Kingstown"],
    "South Carolina": ["Charleston", "Columbia", "North Charleston", "Mount Pleasant", "Rock Hill", "Greenville", "Summerville", "Goose Creek", "Sumter", "Hilton Head Island", "Spartanburg", "Florence", "Myrtle Beach"],
    "South Dakota": ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings", "Watertown", "Mitchell", "Yankton", "Pierre", "Huron", "Vermillion"],
    "Tennessee": ["Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville", "Murfreesboro", "Franklin", "Jackson", "Johnson City", "Bartlett", "Hendersonville", "Kingsport", "Collierville", "Smyrna", "Cleveland", "Brentwood", "Spring Hill", "Germantown", "Columbia", "La Vergne", "Gallatin", "Cookeville"],
    "Texas": ["Houston", "San Antonio", "Dallas", "Austin", "Fort Worth", "El Paso", "Arlington", "Corpus Christi", "Plano", "Laredo", "Lubbock", "Garland", "Irving", "Amarillo", "Grand Prairie", "Brownsville", "McKinney", "Frisco", "Pasadena", "Mesquite", "Killeen", "McAllen", "Waco", "Denton", "Midland", "Carrollton", "Round Rock", "Abilene", "Pearland", "Richardson", "Odessa", "Sugar Land", "Beaumont", "The Woodlands", "College Station", "Lewisville", "League City", "Tyler", "Allen", "Wichita Falls", "San Angelo", "Edinburg", "Conroe", "New Braunfels", "Flower Mound", "Temple", "Bryan", "Missouri City", "North Richland Hills", "Pharr", "Cedar Park", "Baytown", "Pflugerville", "Georgetown", "Longview", "Mission", "San Marcos", "Harlingen", "Rowlett", "Mansfield", "Rockwall", "Euless", "Port Arthur", "Burleson", "Victoria", "Cedar Hill", "Grapevine", "Galveston", "Keller", "Wylie", "DeSoto", "Coppell", "Huntsville", "Haltom City", "Sherman", "Kyle", "Leander", "Duncanville"],
    "Utah": ["Salt Lake City", "West Valley City", "Provo", "West Jordan", "Orem", "Sandy", "Ogden", "St. George", "Layton", "South Jordan", "Lehi", "Millcreek", "Taylorsville", "Logan", "Murray", "Draper", "Bountiful", "Riverton", "Herriman", "Spanish Fork", "Roy", "Pleasant Grove", "Cottonwood Heights", "Tooele"],
    "Vermont": ["Burlington", "South Burlington", "Rutland", "Essex Junction", "Barre", "Montpelier", "Winooski", "St. Albans", "Newport", "Vergennes"],
    "Virginia": ["Virginia Beach", "Norfolk", "Chesapeake", "Richmond", "Newport News", "Alexandria", "Hampton", "Roanoke", "Portsmouth", "Suffolk", "Lynchburg", "Harrisonburg", "Leesburg", "Charlottesville", "Danville", "Manassas", "Fredericksburg", "Winchester"],
    "Washington": ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue", "Kent", "Everett", "Renton", "Spokane Valley", "Federal Way", "Yakima", "Bellingham", "Kirkland", "Auburn", "Kennewick", "Redmond", "Sammamish", "Lacey", "Burien", "Olympia", "Pasco", "Richland", "Edmonds", "Marysville", "Lake Stevens", "Bremerton", "Shoreline", "South Hill", "Lynnwood", "Bothell", "Lakewood", "Puyallup", "Longview", "Issaquah", "Wenatchee", "Mount Vernon", "University Place", "Pullman", "Walla Walla"],
    "West Virginia": ["Charleston", "Huntington", "Morgantown", "Parkersburg", "Wheeling", "Weirton", "Fairmont", "Martinsburg", "Beckley", "Clarksburg"],
    "Wisconsin": ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine", "Appleton", "Waukesha", "Oshkosh", "Eau Claire", "Janesville", "West Allis", "La Crosse", "Sheboygan", "Wauwatosa", "Fond du Lac", "New Berlin", "Wausau", "Brookfield", "Greenfield", "Beloit", "Franklin", "Oak Creek", "Manitowoc", "West Bend", "Sun Prairie", "Superior", "Fitchburg", "Stevens Point", "Neenah", "Caledonia", "Mequon", "Watertown", "De Pere", "Muskego"],
    "Wyoming": ["Cheyenne", "Casper", "Laramie", "Gillette", "Rock Springs", "Sheridan", "Green River", "Evanston", "Riverton", "Cody"],
    "District of Columbia": ["Washington"],
  },
  GB: {
    "England": ["London", "Birmingham", "Manchester", "Liverpool", "Leeds", "Sheffield", "Bristol", "Newcastle", "Nottingham", "Leicester", "Southampton", "Brighton", "Portsmouth", "Plymouth", "Reading", "Derby", "Wolverhampton", "Coventry", "Bradford", "Stoke-on-Trent", "York", "Oxford", "Cambridge", "Norwich", "Exeter", "Bath", "Canterbury", "Chester", "Durham", "Winchester", "Sunderland", "Middlesbrough", "Milton Keynes", "Peterborough", "Northampton", "Luton", "Bolton", "Stockport", "Warrington", "Blackpool", "Preston"],
    "Scotland": ["Edinburgh", "Glasgow", "Aberdeen", "Dundee", "Inverness", "Stirling", "Perth", "Paisley", "Livingston", "Dunfermline", "Kilmarnock", "Greenock", "Ayr", "Falkirk", "Hamilton", "East Kilbride"],
    "Wales": ["Cardiff", "Swansea", "Newport", "Bangor", "St Davids", "Wrexham", "Barry", "Neath", "Cwmbran", "Pontypridd", "Caerphilly", "Llanelli", "Aberystwyth", "Rhyl"],
    "Northern Ireland": ["Belfast", "Londonderry", "Lisburn", "Newry", "Bangor", "Craigavon", "Newtownabbey", "Castlereagh", "Ballymena", "Carrickfergus"],
  },
  CA: {
    "Alberta": ["Calgary", "Edmonton", "Red Deer", "Lethbridge", "St. Albert", "Medicine Hat", "Grande Prairie", "Airdrie", "Spruce Grove", "Leduc", "Fort McMurray", "Lloydminster", "Camrose", "Brooks", "Cold Lake"],
    "British Columbia": ["Vancouver", "Victoria", "Surrey", "Burnaby", "Richmond", "Abbotsford", "Coquitlam", "Kelowna", "Langley", "Saanich", "Delta", "Kamloops", "Nanaimo", "Chilliwack", "Maple Ridge", "Prince George", "New Westminster", "Port Coquitlam", "Vernon", "Courtenay", "Penticton", "Duncan", "Campbell River"],
    "Manitoba": ["Winnipeg", "Brandon", "Steinbach", "Thompson", "Portage la Prairie", "Winkler", "Selkirk", "Morden", "Dauphin"],
    "New Brunswick": ["Moncton", "Saint John", "Fredericton", "Dieppe", "Miramichi", "Edmundston", "Bathurst", "Campbellton"],
    "Newfoundland and Labrador": ["St. John's", "Mount Pearl", "Corner Brook", "Conception Bay South", "Paradise", "Grand Falls-Windsor", "Gander", "Labrador City"],
    "Nova Scotia": ["Halifax", "Dartmouth", "Sydney", "Truro", "New Glasgow", "Glace Bay", "Kentville", "Amherst", "Bridgewater"],
    "Ontario": ["Toronto", "Ottawa", "Mississauga", "Brampton", "Hamilton", "London", "Markham", "Vaughan", "Kitchener", "Windsor", "Richmond Hill", "Oakville", "Burlington", "Greater Sudbury", "Oshawa", "Barrie", "St. Catharines", "Cambridge", "Kingston", "Guelph", "Thunder Bay", "Waterloo", "Brantford", "Pickering", "Whitby", "Niagara Falls", "Ajax", "Milton", "Newmarket", "Peterborough", "Sarnia", "Sault Ste. Marie", "North Bay", "Welland", "Belleville", "Cornwall", "Chatham-Kent", "Georgetown", "Stratford", "Leamington"],
    "Prince Edward Island": ["Charlottetown", "Summerside", "Stratford", "Cornwall", "Montague", "Kensington"],
    "Quebec": ["Montreal", "Quebec City", "Laval", "Gatineau", "Longueuil", "Sherbrooke", "Saguenay", "Lévis", "Trois-Rivières", "Terrebonne", "Saint-Jean-sur-Richelieu", "Repentigny", "Brossard", "Drummondville", "Saint-Jérôme", "Granby", "Blainville", "Saint-Hyacinthe", "Shawinigan", "Dollard-des-Ormeaux", "Rimouski", "Châteauguay", "Saint-Eustache", "Mascouche", "Victoriaville", "Rouyn-Noranda", "Salaberry-de-Valleyfield"],
    "Saskatchewan": ["Saskatoon", "Regina", "Prince Albert", "Moose Jaw", "Swift Current", "Yorkton", "North Battleford", "Estevan", "Weyburn", "Lloydminster"],
    "Northwest Territories": ["Yellowknife", "Hay River", "Inuvik", "Fort Smith"],
    "Nunavut": ["Iqaluit", "Rankin Inlet", "Arviat", "Baker Lake", "Cambridge Bay"],
    "Yukon": ["Whitehorse", "Dawson City", "Watson Lake", "Haines Junction"],
  },
  AU: {
    "New South Wales": ["Sydney", "Newcastle", "Central Coast", "Wollongong", "Maitland", "Coffs Harbour", "Wagga Wagga", "Port Macquarie", "Tamworth", "Orange", "Dubbo", "Albury", "Bathurst", "Lismore", "Nowra", "Queanbeyan", "Armidale", "Ballina", "Grafton", "Broken Hill", "Taree"],
    "Victoria": ["Melbourne", "Geelong", "Ballarat", "Bendigo", "Shepparton", "Mildura", "Wodonga", "Warrnambool", "Traralgon", "Wangaratta", "Horsham", "Sale", "Frankston", "Sunbury", "Melton"],
    "Queensland": ["Brisbane", "Gold Coast", "Sunshine Coast", "Townsville", "Cairns", "Toowoomba", "Mackay", "Rockhampton", "Bundaberg", "Hervey Bay", "Gladstone", "Ipswich", "Logan City", "Redland City", "Caloundra", "Mount Isa"],
    "Western Australia": ["Perth", "Mandurah", "Bunbury", "Rockingham", "Geraldton", "Kalgoorlie", "Albany", "Busselton", "Karratha", "Port Hedland", "Broome", "Esperance"],
    "South Australia": ["Adelaide", "Mount Gambier", "Whyalla", "Murray Bridge", "Port Lincoln", "Port Augusta", "Port Pirie", "Victor Harbor", "Gawler"],
    "Tasmania": ["Hobart", "Launceston", "Devonport", "Burnie", "Kingston", "Ulverstone", "Glenorchy", "New Norfolk"],
    "Australian Capital Territory": ["Canberra", "Queanbeyan"],
    "Northern Territory": ["Darwin", "Alice Springs", "Palmerston", "Katherine", "Tennant Creek", "Nhulunbuy"],
  },
  AE: {
    "Abu Dhabi": ["Abu Dhabi", "Al Ain", "Al Dhafra", "Madinat Zayed", "Liwa Oasis", "Ruwais"],
    "Ajman": ["Ajman", "Masfout", "Manama"],
    "Dubai": ["Dubai", "Jebel Ali", "Hatta"],
    "Fujairah": ["Fujairah", "Dibba Al-Fujairah", "Masafi"],
    "Ras Al Khaimah": ["Ras Al Khaimah", "Al Jazirah Al Hamra", "Digdaga"],
    "Sharjah": ["Sharjah", "Khor Fakkan", "Kalba", "Dibba Al-Hisn", "Al Dhaid"],
    "Umm Al Quwain": ["Umm Al Quwain", "Falaj Al Mualla"],
  },
  SG: {
    "Central Region": ["Singapore", "Orchard", "Marina Bay", "Sentosa", "Chinatown", "Little India", "Bugis", "City Hall"],
    "East Region": ["Tampines", "Pasir Ris", "Bedok", "Changi"],
    "North Region": ["Woodlands", "Sembawang", "Yishun", "Mandai"],
    "North-East Region": ["Hougang", "Sengkang", "Punggol", "Serangoon"],
    "West Region": ["Jurong East", "Jurong West", "Clementi", "Bukit Batok", "Choa Chu Kang", "Bukit Panjang", "Tuas"],
  },
  DE: {
    "Baden-Württemberg": ["Stuttgart", "Mannheim", "Karlsruhe", "Freiburg", "Heidelberg", "Ulm", "Heilbronn", "Pforzheim", "Reutlingen", "Esslingen", "Ludwigsburg", "Tübingen", "Villingen-Schwenningen", "Konstanz", "Aalen", "Sindelfingen", "Schwäbisch Gmünd", "Offenburg", "Göppingen", "Baden-Baden"],
    "Bavaria": ["Munich", "Nuremberg", "Augsburg", "Regensburg", "Ingolstadt", "Würzburg", "Fürth", "Erlangen", "Bamberg", "Bayreuth", "Landshut", "Aschaffenburg", "Kempten", "Rosenheim", "Passau", "Straubing", "Neu-Ulm", "Freising"],
    "Berlin": ["Berlin"],
    "Brandenburg": ["Potsdam", "Cottbus", "Brandenburg an der Havel", "Frankfurt (Oder)", "Oranienburg", "Falkensee", "Bernau", "Eberswalde", "Königs Wusterhausen"],
    "Bremen": ["Bremen", "Bremerhaven"],
    "Hamburg": ["Hamburg"],
    "Hesse": ["Frankfurt", "Wiesbaden", "Kassel", "Darmstadt", "Offenbach", "Hanau", "Gießen", "Marburg", "Fulda", "Rüsselsheim", "Wetzlar", "Bad Homburg"],
    "Lower Saxony": ["Hanover", "Braunschweig", "Osnabrück", "Oldenburg", "Göttingen", "Wolfsburg", "Salzgitter", "Hildesheim", "Wilhelmshaven", "Delmenhorst", "Emden", "Celle", "Lüneburg", "Hameln", "Lingen"],
    "Mecklenburg-Vorpommern": ["Rostock", "Schwerin", "Neubrandenburg", "Stralsund", "Greifswald", "Wismar", "Güstrow", "Waren"],
    "North Rhine-Westphalia": ["Cologne", "Düsseldorf", "Dortmund", "Essen", "Duisburg", "Bochum", "Wuppertal", "Bielefeld", "Bonn", "Münster", "Mönchengladbach", "Gelsenkirchen", "Aachen", "Krefeld", "Oberhausen", "Hagen", "Hamm", "Mülheim", "Leverkusen", "Solingen", "Herne", "Neuss", "Paderborn", "Recklinghausen", "Bottrop", "Remscheid", "Bergisch Gladbach", "Moers", "Siegen", "Witten", "Gütersloh", "Iserlohn"],
    "Rhineland-Palatinate": ["Mainz", "Ludwigshafen", "Koblenz", "Trier", "Kaiserslautern", "Worms", "Neuwied", "Neustadt", "Speyer", "Bad Kreuznach", "Frankenthal", "Landau"],
    "Saarland": ["Saarbrücken", "Neunkirchen", "Homburg", "Völklingen", "St. Ingbert", "Saarlouis"],
    "Saxony": ["Leipzig", "Dresden", "Chemnitz", "Zwickau", "Plauen", "Görlitz", "Freiberg", "Bautzen", "Pirna", "Meissen"],
    "Saxony-Anhalt": ["Halle", "Magdeburg", "Dessau-Roßlau", "Wittenberg", "Halberstadt", "Stendal", "Wernigerode", "Bernburg", "Schönebeck"],
    "Schleswig-Holstein": ["Kiel", "Lübeck", "Flensburg", "Neumünster", "Norderstedt", "Elmshorn", "Pinneberg", "Itzehoe", "Wedel", "Ahrensburg"],
    "Thuringia": ["Erfurt", "Jena", "Gera", "Weimar", "Gotha", "Eisenach", "Suhl", "Nordhausen", "Mühlhausen", "Altenburg"],
  },
  FR: {
    "Auvergne-Rhône-Alpes": ["Lyon", "Saint-Étienne", "Grenoble", "Villeurbanne", "Clermont-Ferrand", "Valence", "Chambéry", "Annecy", "Vénissieux", "Bourg-en-Bresse"],
    "Bourgogne-Franche-Comté": ["Dijon", "Besançon", "Belfort", "Chalon-sur-Saône", "Auxerre", "Nevers", "Mâcon", "Montbéliard", "Le Creusot", "Sens"],
    "Brittany": ["Rennes", "Brest", "Quimper", "Lorient", "Vannes", "Saint-Malo", "Saint-Brieuc", "Lanester", "Fougères", "Lannion"],
    "Centre-Val de Loire": ["Tours", "Orléans", "Bourges", "Blois", "Chartres", "Châteauroux", "Joué-lès-Tours", "Dreux", "Vierzon", "Olivet"],
    "Corsica": ["Ajaccio", "Bastia", "Porto-Vecchio", "Calvi", "Corte", "Bonifacio"],
    "Grand Est": ["Strasbourg", "Reims", "Metz", "Mulhouse", "Nancy", "Colmar", "Troyes", "Charleville-Mézières", "Épinal", "Châlons-en-Champagne", "Thionville", "Haguenau", "Schiltigheim"],
    "Hauts-de-France": ["Lille", "Amiens", "Roubaix", "Dunkirk", "Tourcoing", "Calais", "Boulogne-sur-Mer", "Arras", "Valenciennes", "Lens", "Liévin", "Villeneuve-d'Ascq", "Beauvais", "Douai", "Compiègne", "Saint-Quentin", "Laon"],
    "Île-de-France": ["Paris", "Boulogne-Billancourt", "Saint-Denis", "Argenteuil", "Montreuil", "Nanterre", "Créteil", "Versailles", "Vitry-sur-Seine", "Colombes", "Asnières-sur-Seine", "Aulnay-sous-Bois", "Rueil-Malmaison", "Aubervilliers", "Champigny-sur-Marne", "Saint-Maur-des-Fossés", "Drancy", "Issy-les-Moulineaux", "Noisy-le-Grand", "Levallois-Perret", "Neuilly-sur-Seine", "Antony", "Clichy", "Ivry-sur-Seine", "Cergy", "Sarcelles", "Bobigny", "Épinay-sur-Seine", "Meaux", "Pantin", "Évry"],
    "Normandy": ["Rouen", "Le Havre", "Caen", "Cherbourg", "Évreux", "Dieppe", "Alençon", "Lisieux", "Saint-Lô", "Coutances"],
    "Nouvelle-Aquitaine": ["Bordeaux", "Limoges", "Poitiers", "Mérignac", "La Rochelle", "Pau", "Pessac", "Niort", "Bayonne", "Angoulême", "Brive-la-Gaillarde", "Agen", "Périgueux", "Mont-de-Marsan"],
    "Occitania": ["Toulouse", "Montpellier", "Nîmes", "Perpignan", "Béziers", "Carcassonne", "Tarbes", "Albi", "Narbonne", "Castres", "Sète", "Rodez", "Montauban", "Auch", "Cahors"],
    "Pays de la Loire": ["Nantes", "Angers", "Le Mans", "Saint-Nazaire", "Cholet", "La Roche-sur-Yon", "Laval", "Saint-Herblain", "Rezé", "Saumur"],
    "Provence-Alpes-Côte d'Azur": ["Marseille", "Nice", "Toulon", "Aix-en-Provence", "Avignon", "Antibes", "Cannes", "Fréjus", "Hyères", "Arles", "Gap", "Grasse", "La Seyne-sur-Mer", "Martigues", "Aubagne", "Salon-de-Provence", "Istres", "Cagnes-sur-Mer", "Draguignan", "Le Cannet"],
  },
};
