// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cert-fonts/LibreCaslon.tsx": () => import("../components/mockups/cert-fonts/LibreCaslon.tsx"),
  "./components/mockups/cert-fonts/MarcellusSC.tsx": () => import("../components/mockups/cert-fonts/MarcellusSC.tsx"),
  "./components/mockups/cert-fonts/YesevaOne.tsx": () => import("../components/mockups/cert-fonts/YesevaOne.tsx")
};
