export const countriesData = [
  { name: "Afghanistan", code: "AF" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "Andorra", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Antigua and Barbuda", code: "AG" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bahamas", code: "BS" },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY" },
  { name: "Belgium", code: "BE" },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bhutan", code: "BT" },
  { name: "Bolivia", code: "BO" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Botswana", code: "BW" },
  { name: "Brazil", code: "BR" },
  { name: "Brunei", code: "BN" },
  { name: "Bulgaria", code: "BG" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Cambodia", code: "KH" },
  { name: "Cameroon", code: "CM" },
  { name: "Canada", code: "CA" },
  { name: "Cape Verde", code: "CV" },
  { name: "Central African Republic", code: "CF" },
  { name: "Chad", code: "TD" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN" },
  { name: "Colombia", code: "CO" },
  { name: "Comoros", code: "KM" },
  { name: "Congo", code: "CG" },
  { name: "Costa Rica", code: "CR" },
  { name: "Croatia", code: "HR" },
  { name: "Cuba", code: "CU" },
  { name: "Cyprus", code: "CY" },
  { name: "Czech Republic", code: "CZ" },
  { name: "Denmark", code: "DK" },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "Dominican Republic", code: "DO" },
  { name: "East Timor", code: "TL" },
  { name: "Ecuador", code: "EC" },
  { name: "Egypt", code: "EG" },
  { name: "El Salvador", code: "SV" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Eritrea", code: "ER" },
  { name: "Estonia", code: "EE" },
  { name: "Eswatini", code: "SZ" },
  { name: "Ethiopia", code: "ET" },
  { name: "Fiji", code: "FJ" },
  { name: "Finland", code: "FI" },
  { name: "France", code: "FR" },
  { name: "Gabon", code: "GA" },
  { name: "Gambia", code: "GM" },
  { name: "Georgia", code: "GE" },
  { name: "Germany", code: "DE" },
  { name: "Ghana", code: "GH" },
  { name: "Greece", code: "GR" },
  { name: "Grenada", code: "GD" },
  { name: "Guatemala", code: "GT" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Guyana", code: "GY" },
  { name: "Haiti", code: "HT" },
  { name: "Honduras", code: "HN" },
  { name: "Hungary", code: "HU" },
  { name: "Iceland", code: "IS" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE" },
  { name: "Israel", code: "IL" },
  { name: "Italy", code: "IT" },
  { name: "Ivory Coast", code: "CI" },
  { name: "Jamaica", code: "JM" },
  { name: "Japan", code: "JP" },
  { name: "Jordan", code: "JO" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kiribati", code: "KI" },
  { name: "Kosovo", code: "XK" },
  { name: "Kuwait", code: "KW" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: "Laos", code: "LA" },
  { name: "Latvia", code: "LV" },
  { name: "Lebanon", code: "LB" },
  { name: "Lesotho", code: "LS" },
  { name: "Liberia", code: "LR" },
  { name: "Libya", code: "LY" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malaysia", code: "MY" },
  { name: "Maldives", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Marshall Islands", code: "MH" },
  { name: "Mauritania", code: "MR" },
  { name: "Mauritius", code: "MU" },
  { name: "Mexico", code: "MX" },
  { name: "Micronesia", code: "FM" },
  { name: "Moldova", code: "MD" },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN" },
  { name: "Montenegro", code: "ME" },
  { name: "Morocco", code: "MA" },
  { name: "Mozambique", code: "MZ" },
  { name: "Myanmar", code: "MM" },
  { name: "Namibia", code: "NA" },
  { name: "Nauru", code: "NR" },
  { name: "Nepal", code: "NP" },
  { name: "Netherlands", code: "NL" },
  { name: "New Zealand", code: "NZ" },
  { name: "Nicaragua", code: "NI" },
  { name: "Niger", code: "NE" },
  { name: "Nigeria", code: "NG" },
  { name: "North Korea", code: "KP" },
  { name: "North Macedonia", code: "MK" },
  { name: "Norway", code: "NO" },
  { name: "Oman", code: "OM" },
  { name: "Pakistan", code: "PK" },
  { name: "Palau", code: "PW" },
  { name: "Palestine", code: "PS" },
  { name: "Panama", code: "PA" },
  { name: "Papua New Guinea", code: "PG" },
  { name: "Paraguay", code: "PY" },
  { name: "Peru", code: "PE" },
  { name: "Philippines", code: "PH" },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Qatar", code: "QA" },
  { name: "Romania", code: "RO" },
  { name: "Russia", code: "RU" },
  { name: "Rwanda", code: "RW" },
  { name: "Saint Kitts and Nevis", code: "KN" },
  { name: "Saint Lucia", code: "LC" },
  { name: "Saint Vincent and the Grenadines", code: "VC" },
  { name: "Samoa", code: "WS" },
  { name: "San Marino", code: "SM" },
  { name: "Sao Tome and Principe", code: "ST" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia", code: "RS" },
  { name: "Seychelles", code: "SC" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Singapore", code: "SG" },
  { name: "Slovakia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "Solomon Islands", code: "SB" },
  { name: "Somalia", code: "SO" },
  { name: "South Africa", code: "ZA" },
  { name: "South Korea", code: "KR" },
  { name: "South Sudan", code: "SS" },
  { name: "Spain", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sudan", code: "SD" },
  { name: "Suriname", code: "SR" },
  { name: "Sweden", code: "SE" },
  { name: "Switzerland", code: "CH" },
  { name: "Syria", code: "SY" },
  { name: "Taiwan", code: "TW" },
  { name: "Tajikistan", code: "TJ" },
  { name: "Tanzania", code: "TZ" },
  { name: "Thailand", code: "TH" },
  { name: "Togo", code: "TG" },
  { name: "Tonga", code: "TO" },
  { name: "Trinidad and Tobago", code: "TT" },
  { name: "Tunisia", code: "TN" },
  { name: "Turkey", code: "TR" },
  { name: "Turkmenistan", code: "TM" },
  { name: "Tuvalu", code: "TV" },
  { name: "Uganda", code: "UG" },
  { name: "Ukraine", code: "UA" },
  { name: "United Arab Emirates", code: "AE" },
  { name: "United Kingdom", code: "GB" },
  { name: "United States", code: "US" },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Vanuatu", code: "VU" },
  { name: "Vatican City", code: "VA" },
  { name: "Venezuela", code: "VE" },
  { name: "Vietnam", code: "VN" },
  { name: "Yemen", code: "YE" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
];

export const statesData: Record<string, { name: string; code?: string }[]> = {
  IN: [
    { name: "Andhra Pradesh", code: "AP" },
    { name: "Arunachal Pradesh", code: "AR" },
    { name: "Assam", code: "AS" },
    { name: "Bihar", code: "BR" },
    { name: "Chhattisgarh", code: "CG" },
    { name: "Goa", code: "GA" },
    { name: "Gujarat", code: "GJ" },
    { name: "Haryana", code: "HR" },
    { name: "Himachal Pradesh", code: "HP" },
    { name: "Jharkhand", code: "JH" },
    { name: "Karnataka", code: "KA" },
    { name: "Kerala", code: "KL" },
    { name: "Madhya Pradesh", code: "MP" },
    { name: "Maharashtra", code: "MH" },
    { name: "Manipur", code: "MN" },
    { name: "Meghalaya", code: "ML" },
    { name: "Mizoram", code: "MZ" },
    { name: "Nagaland", code: "NL" },
    { name: "Odisha", code: "OD" },
    { name: "Punjab", code: "PB" },
    { name: "Rajasthan", code: "RJ" },
    { name: "Sikkim", code: "SK" },
    { name: "Tamil Nadu", code: "TN" },
    { name: "Telangana", code: "TS" },
    { name: "Tripura", code: "TR" },
    { name: "Uttar Pradesh", code: "UP" },
    { name: "Uttarakhand", code: "UK" },
    { name: "West Bengal", code: "WB" },
    { name: "Andaman and Nicobar Islands", code: "AN" },
    { name: "Chandigarh", code: "CH" },
    { name: "Dadra and Nagar Haveli and Daman and Diu", code: "DN" },
    { name: "Delhi", code: "DL" },
    { name: "Jammu and Kashmir", code: "JK" },
    { name: "Ladakh", code: "LA" },
    { name: "Lakshadweep", code: "LD" },
    { name: "Puducherry", code: "PY" },
  ],
  US: [
    { name: "Alabama", code: "AL" },
    { name: "Alaska", code: "AK" },
    { name: "Arizona", code: "AZ" },
    { name: "Arkansas", code: "AR" },
    { name: "California", code: "CA" },
    { name: "Colorado", code: "CO" },
    { name: "Connecticut", code: "CT" },
    { name: "Delaware", code: "DE" },
    { name: "Florida", code: "FL" },
    { name: "Georgia", code: "GA" },
    { name: "Hawaii", code: "HI" },
    { name: "Idaho", code: "ID" },
    { name: "Illinois", code: "IL" },
    { name: "Indiana", code: "IN" },
    { name: "Iowa", code: "IA" },
    { name: "Kansas", code: "KS" },
    { name: "Kentucky", code: "KY" },
    { name: "Louisiana", code: "LA" },
    { name: "Maine", code: "ME" },
    { name: "Maryland", code: "MD" },
    { name: "Massachusetts", code: "MA" },
    { name: "Michigan", code: "MI" },
    { name: "Minnesota", code: "MN" },
    { name: "Mississippi", code: "MS" },
    { name: "Missouri", code: "MO" },
    { name: "Montana", code: "MT" },
    { name: "Nebraska", code: "NE" },
    { name: "Nevada", code: "NV" },
    { name: "New Hampshire", code: "NH" },
    { name: "New Jersey", code: "NJ" },
    { name: "New Mexico", code: "NM" },
    { name: "New York", code: "NY" },
    { name: "North Carolina", code: "NC" },
    { name: "North Dakota", code: "ND" },
    { name: "Ohio", code: "OH" },
    { name: "Oklahoma", code: "OK" },
    { name: "Oregon", code: "OR" },
    { name: "Pennsylvania", code: "PA" },
    { name: "Rhode Island", code: "RI" },
    { name: "South Carolina", code: "SC" },
    { name: "South Dakota", code: "SD" },
    { name: "Tennessee", code: "TN" },
    { name: "Texas", code: "TX" },
    { name: "Utah", code: "UT" },
    { name: "Vermont", code: "VT" },
    { name: "Virginia", code: "VA" },
    { name: "Washington", code: "WA" },
    { name: "West Virginia", code: "WV" },
    { name: "Wisconsin", code: "WI" },
    { name: "Wyoming", code: "WY" },
    { name: "District of Columbia", code: "DC" },
  ],
  GB: [
    { name: "England", code: "ENG" },
    { name: "Scotland", code: "SCT" },
    { name: "Wales", code: "WLS" },
    { name: "Northern Ireland", code: "NIR" },
  ],
  CA: [
    { name: "Alberta", code: "AB" },
    { name: "British Columbia", code: "BC" },
    { name: "Manitoba", code: "MB" },
    { name: "New Brunswick", code: "NB" },
    { name: "Newfoundland and Labrador", code: "NL" },
    { name: "Nova Scotia", code: "NS" },
    { name: "Ontario", code: "ON" },
    { name: "Prince Edward Island", code: "PE" },
    { name: "Quebec", code: "QC" },
    { name: "Saskatchewan", code: "SK" },
    { name: "Northwest Territories", code: "NT" },
    { name: "Nunavut", code: "NU" },
    { name: "Yukon", code: "YT" },
  ],
  AU: [
    { name: "New South Wales", code: "NSW" },
    { name: "Victoria", code: "VIC" },
    { name: "Queensland", code: "QLD" },
    { name: "Western Australia", code: "WA" },
    { name: "South Australia", code: "SA" },
    { name: "Tasmania", code: "TAS" },
    { name: "Australian Capital Territory", code: "ACT" },
    { name: "Northern Territory", code: "NT" },
  ],
  DE: [
    { name: "Baden-Württemberg", code: "BW" },
    { name: "Bavaria", code: "BY" },
    { name: "Berlin", code: "BE" },
    { name: "Brandenburg", code: "BB" },
    { name: "Bremen", code: "HB" },
    { name: "Hamburg", code: "HH" },
    { name: "Hesse", code: "HE" },
    { name: "Lower Saxony", code: "NI" },
    { name: "Mecklenburg-Vorpommern", code: "MV" },
    { name: "North Rhine-Westphalia", code: "NW" },
    { name: "Rhineland-Palatinate", code: "RP" },
    { name: "Saarland", code: "SL" },
    { name: "Saxony", code: "SN" },
    { name: "Saxony-Anhalt", code: "ST" },
    { name: "Schleswig-Holstein", code: "SH" },
    { name: "Thuringia", code: "TH" },
  ],
  FR: [
    { name: "Auvergne-Rhône-Alpes", code: "ARA" },
    { name: "Bourgogne-Franche-Comté", code: "BFC" },
    { name: "Brittany", code: "BRE" },
    { name: "Centre-Val de Loire", code: "CVL" },
    { name: "Corsica", code: "COR" },
    { name: "Grand Est", code: "GES" },
    { name: "Hauts-de-France", code: "HDF" },
    { name: "Île-de-France", code: "IDF" },
    { name: "Normandy", code: "NOR" },
    { name: "Nouvelle-Aquitaine", code: "NAQ" },
    { name: "Occitania", code: "OCC" },
    { name: "Pays de la Loire", code: "PDL" },
    { name: "Provence-Alpes-Côte d'Azur", code: "PAC" },
  ],
  CN: [
    { name: "Anhui", code: "AH" },
    { name: "Beijing", code: "BJ" },
    { name: "Chongqing", code: "CQ" },
    { name: "Fujian", code: "FJ" },
    { name: "Gansu", code: "GS" },
    { name: "Guangdong", code: "GD" },
    { name: "Guangxi", code: "GX" },
    { name: "Guizhou", code: "GZ" },
    { name: "Hainan", code: "HI" },
    { name: "Hebei", code: "HE" },
    { name: "Heilongjiang", code: "HL" },
    { name: "Henan", code: "HA" },
    { name: "Hong Kong", code: "HK" },
    { name: "Hubei", code: "HB" },
    { name: "Hunan", code: "HN" },
    { name: "Inner Mongolia", code: "NM" },
    { name: "Jiangsu", code: "JS" },
    { name: "Jiangxi", code: "JX" },
    { name: "Jilin", code: "JL" },
    { name: "Liaoning", code: "LN" },
    { name: "Macau", code: "MO" },
    { name: "Ningxia", code: "NX" },
    { name: "Qinghai", code: "QH" },
    { name: "Shaanxi", code: "SN" },
    { name: "Shandong", code: "SD" },
    { name: "Shanghai", code: "SH" },
    { name: "Shanxi", code: "SX" },
    { name: "Sichuan", code: "SC" },
    { name: "Tianjin", code: "TJ" },
    { name: "Tibet", code: "XZ" },
    { name: "Xinjiang", code: "XJ" },
    { name: "Yunnan", code: "YN" },
    { name: "Zhejiang", code: "ZJ" },
  ],
  JP: [
    { name: "Hokkaido", code: "01" },
    { name: "Aomori", code: "02" },
    { name: "Iwate", code: "03" },
    { name: "Miyagi", code: "04" },
    { name: "Akita", code: "05" },
    { name: "Yamagata", code: "06" },
    { name: "Fukushima", code: "07" },
    { name: "Ibaraki", code: "08" },
    { name: "Tochigi", code: "09" },
    { name: "Gunma", code: "10" },
    { name: "Saitama", code: "11" },
    { name: "Chiba", code: "12" },
    { name: "Tokyo", code: "13" },
    { name: "Kanagawa", code: "14" },
    { name: "Niigata", code: "15" },
    { name: "Toyama", code: "16" },
    { name: "Ishikawa", code: "17" },
    { name: "Fukui", code: "18" },
    { name: "Yamanashi", code: "19" },
    { name: "Nagano", code: "20" },
    { name: "Gifu", code: "21" },
    { name: "Shizuoka", code: "22" },
    { name: "Aichi", code: "23" },
    { name: "Mie", code: "24" },
    { name: "Shiga", code: "25" },
    { name: "Kyoto", code: "26" },
    { name: "Osaka", code: "27" },
    { name: "Hyogo", code: "28" },
    { name: "Nara", code: "29" },
    { name: "Wakayama", code: "30" },
    { name: "Tottori", code: "31" },
    { name: "Shimane", code: "32" },
    { name: "Okayama", code: "33" },
    { name: "Hiroshima", code: "34" },
    { name: "Yamaguchi", code: "35" },
    { name: "Tokushima", code: "36" },
    { name: "Kagawa", code: "37" },
    { name: "Ehime", code: "38" },
    { name: "Kochi", code: "39" },
    { name: "Fukuoka", code: "40" },
    { name: "Saga", code: "41" },
    { name: "Nagasaki", code: "42" },
    { name: "Kumamoto", code: "43" },
    { name: "Oita", code: "44" },
    { name: "Miyazaki", code: "45" },
    { name: "Kagoshima", code: "46" },
    { name: "Okinawa", code: "47" },
  ],
  BR: [
    { name: "Acre", code: "AC" },
    { name: "Alagoas", code: "AL" },
    { name: "Amapá", code: "AP" },
    { name: "Amazonas", code: "AM" },
    { name: "Bahia", code: "BA" },
    { name: "Ceará", code: "CE" },
    { name: "Distrito Federal", code: "DF" },
    { name: "Espírito Santo", code: "ES" },
    { name: "Goiás", code: "GO" },
    { name: "Maranhão", code: "MA" },
    { name: "Mato Grosso", code: "MT" },
    { name: "Mato Grosso do Sul", code: "MS" },
    { name: "Minas Gerais", code: "MG" },
    { name: "Pará", code: "PA" },
    { name: "Paraíba", code: "PB" },
    { name: "Paraná", code: "PR" },
    { name: "Pernambuco", code: "PE" },
    { name: "Piauí", code: "PI" },
    { name: "Rio de Janeiro", code: "RJ" },
    { name: "Rio Grande do Norte", code: "RN" },
    { name: "Rio Grande do Sul", code: "RS" },
    { name: "Rondônia", code: "RO" },
    { name: "Roraima", code: "RR" },
    { name: "Santa Catarina", code: "SC" },
    { name: "São Paulo", code: "SP" },
    { name: "Sergipe", code: "SE" },
    { name: "Tocantins", code: "TO" },
  ],
  MX: [
    { name: "Aguascalientes", code: "AGU" },
    { name: "Baja California", code: "BCN" },
    { name: "Baja California Sur", code: "BCS" },
    { name: "Campeche", code: "CAM" },
    { name: "Chiapas", code: "CHP" },
    { name: "Chihuahua", code: "CHH" },
    { name: "Coahuila", code: "COA" },
    { name: "Colima", code: "COL" },
    { name: "Durango", code: "DUR" },
    { name: "Guanajuato", code: "GUA" },
    { name: "Guerrero", code: "GRO" },
    { name: "Hidalgo", code: "HID" },
    { name: "Jalisco", code: "JAL" },
    { name: "Mexico City", code: "CMX" },
    { name: "Mexico State", code: "MEX" },
    { name: "Michoacán", code: "MIC" },
    { name: "Morelos", code: "MOR" },
    { name: "Nayarit", code: "NAY" },
    { name: "Nuevo León", code: "NLE" },
    { name: "Oaxaca", code: "OAX" },
    { name: "Puebla", code: "PUE" },
    { name: "Querétaro", code: "QUE" },
    { name: "Quintana Roo", code: "ROO" },
    { name: "San Luis Potosí", code: "SLP" },
    { name: "Sinaloa", code: "SIN" },
    { name: "Sonora", code: "SON" },
    { name: "Tabasco", code: "TAB" },
    { name: "Tamaulipas", code: "TAM" },
    { name: "Tlaxcala", code: "TLA" },
    { name: "Veracruz", code: "VER" },
    { name: "Yucatán", code: "YUC" },
    { name: "Zacatecas", code: "ZAC" },
  ],
  AE: [
    { name: "Abu Dhabi", code: "AZ" },
    { name: "Ajman", code: "AJ" },
    { name: "Dubai", code: "DU" },
    { name: "Fujairah", code: "FU" },
    { name: "Ras Al Khaimah", code: "RK" },
    { name: "Sharjah", code: "SH" },
    { name: "Umm Al Quwain", code: "UQ" },
  ],
  SG: [
    { name: "Central Region", code: "01" },
    { name: "East Region", code: "02" },
    { name: "North Region", code: "03" },
    { name: "North-East Region", code: "04" },
    { name: "West Region", code: "05" },
  ],
  RU: [
    { name: "Moscow", code: "MOW" },
    { name: "Saint Petersburg", code: "SPE" },
    { name: "Moscow Oblast", code: "MOS" },
    { name: "Krasnodar Krai", code: "KDA" },
    { name: "Sverdlovsk Oblast", code: "SVE" },
    { name: "Rostov Oblast", code: "ROS" },
    { name: "Republic of Tatarstan", code: "TA" },
    { name: "Chelyabinsk Oblast", code: "CHE" },
    { name: "Nizhny Novgorod Oblast", code: "NIZ" },
    { name: "Samara Oblast", code: "SAM" },
  ],
  ZA: [
    { name: "Eastern Cape", code: "EC" },
    { name: "Free State", code: "FS" },
    { name: "Gauteng", code: "GP" },
    { name: "KwaZulu-Natal", code: "KZN" },
    { name: "Limpopo", code: "LP" },
    { name: "Mpumalanga", code: "MP" },
    { name: "Northern Cape", code: "NC" },
    { name: "North West", code: "NW" },
    { name: "Western Cape", code: "WC" },
  ],
  NG: [
    { name: "Abia", code: "AB" },
    { name: "Adamawa", code: "AD" },
    { name: "Akwa Ibom", code: "AK" },
    { name: "Anambra", code: "AN" },
    { name: "Bauchi", code: "BA" },
    { name: "Bayelsa", code: "BY" },
    { name: "Benue", code: "BE" },
    { name: "Borno", code: "BO" },
    { name: "Cross River", code: "CR" },
    { name: "Delta", code: "DE" },
    { name: "Ebonyi", code: "EB" },
    { name: "Edo", code: "ED" },
    { name: "Ekiti", code: "EK" },
    { name: "Enugu", code: "EN" },
    { name: "FCT Abuja", code: "FC" },
    { name: "Gombe", code: "GO" },
    { name: "Imo", code: "IM" },
    { name: "Jigawa", code: "JI" },
    { name: "Kaduna", code: "KD" },
    { name: "Kano", code: "KN" },
    { name: "Katsina", code: "KT" },
    { name: "Kebbi", code: "KE" },
    { name: "Kogi", code: "KO" },
    { name: "Kwara", code: "KW" },
    { name: "Lagos", code: "LA" },
    { name: "Nasarawa", code: "NA" },
    { name: "Niger", code: "NI" },
    { name: "Ogun", code: "OG" },
    { name: "Ondo", code: "ON" },
    { name: "Osun", code: "OS" },
    { name: "Oyo", code: "OY" },
    { name: "Plateau", code: "PL" },
    { name: "Rivers", code: "RI" },
    { name: "Sokoto", code: "SO" },
    { name: "Taraba", code: "TA" },
    { name: "Yobe", code: "YO" },
    { name: "Zamfara", code: "ZA" },
  ],
  PK: [
    { name: "Balochistan", code: "BA" },
    { name: "Islamabad Capital Territory", code: "IS" },
    { name: "Khyber Pakhtunkhwa", code: "KP" },
    { name: "Punjab", code: "PB" },
    { name: "Sindh", code: "SD" },
    { name: "Azad Kashmir", code: "JK" },
    { name: "Gilgit-Baltistan", code: "GB" },
  ],
  BD: [
    { name: "Barishal", code: "A" },
    { name: "Chattogram", code: "B" },
    { name: "Dhaka", code: "C" },
    { name: "Khulna", code: "D" },
    { name: "Mymensingh", code: "M" },
    { name: "Rajshahi", code: "E" },
    { name: "Rangpur", code: "F" },
    { name: "Sylhet", code: "G" },
  ],
  ID: [
    { name: "Aceh", code: "AC" },
    { name: "Bali", code: "BA" },
    { name: "Banten", code: "BT" },
    { name: "Bengkulu", code: "BE" },
    { name: "Central Java", code: "JT" },
    { name: "Central Kalimantan", code: "KT" },
    { name: "Central Sulawesi", code: "ST" },
    { name: "East Java", code: "JI" },
    { name: "East Kalimantan", code: "KI" },
    { name: "East Nusa Tenggara", code: "NT" },
    { name: "Gorontalo", code: "GO" },
    { name: "Jakarta", code: "JK" },
    { name: "Jambi", code: "JA" },
    { name: "Lampung", code: "LA" },
    { name: "Maluku", code: "MA" },
    { name: "North Kalimantan", code: "KU" },
    { name: "North Maluku", code: "MU" },
    { name: "North Sulawesi", code: "SA" },
    { name: "North Sumatra", code: "SU" },
    { name: "Papua", code: "PA" },
    { name: "Riau", code: "RI" },
    { name: "Riau Islands", code: "KR" },
    { name: "South Kalimantan", code: "KS" },
    { name: "South Sulawesi", code: "SN" },
    { name: "South Sumatra", code: "SS" },
    { name: "Southeast Sulawesi", code: "SG" },
    { name: "West Java", code: "JB" },
    { name: "West Kalimantan", code: "KB" },
    { name: "West Nusa Tenggara", code: "NB" },
    { name: "West Papua", code: "PB" },
    { name: "West Sulawesi", code: "SR" },
    { name: "West Sumatra", code: "SB" },
    { name: "Yogyakarta", code: "YO" },
  ],
  PH: [
    { name: "Metro Manila", code: "NCR" },
    { name: "Ilocos Region", code: "01" },
    { name: "Cagayan Valley", code: "02" },
    { name: "Central Luzon", code: "03" },
    { name: "CALABARZON", code: "04A" },
    { name: "MIMAROPA", code: "04B" },
    { name: "Bicol Region", code: "05" },
    { name: "Western Visayas", code: "06" },
    { name: "Central Visayas", code: "07" },
    { name: "Eastern Visayas", code: "08" },
    { name: "Zamboanga Peninsula", code: "09" },
    { name: "Northern Mindanao", code: "10" },
    { name: "Davao Region", code: "11" },
    { name: "SOCCSKSARGEN", code: "12" },
    { name: "Caraga", code: "13" },
    { name: "BARMM", code: "BARMM" },
    { name: "Cordillera Administrative Region", code: "CAR" },
  ],
  MY: [
    { name: "Johor", code: "JHR" },
    { name: "Kedah", code: "KDH" },
    { name: "Kelantan", code: "KTN" },
    { name: "Kuala Lumpur", code: "KUL" },
    { name: "Labuan", code: "LBN" },
    { name: "Malacca", code: "MLK" },
    { name: "Negeri Sembilan", code: "NSN" },
    { name: "Pahang", code: "PHG" },
    { name: "Penang", code: "PNG" },
    { name: "Perak", code: "PRK" },
    { name: "Perlis", code: "PLS" },
    { name: "Putrajaya", code: "PJY" },
    { name: "Sabah", code: "SBH" },
    { name: "Sarawak", code: "SWK" },
    { name: "Selangor", code: "SGR" },
    { name: "Terengganu", code: "TRG" },
  ],
  TH: [
    { name: "Bangkok", code: "10" },
    { name: "Chiang Mai", code: "50" },
    { name: "Chiang Rai", code: "57" },
    { name: "Chonburi", code: "20" },
    { name: "Khon Kaen", code: "40" },
    { name: "Nakhon Ratchasima", code: "30" },
    { name: "Nonthaburi", code: "12" },
    { name: "Pathum Thani", code: "13" },
    { name: "Phuket", code: "83" },
    { name: "Samut Prakan", code: "11" },
    { name: "Songkhla", code: "90" },
    { name: "Surat Thani", code: "84" },
    { name: "Udon Thani", code: "41" },
  ],
  VN: [
    { name: "An Giang", code: "44" },
    { name: "Ba Ria-Vung Tau", code: "43" },
    { name: "Binh Duong", code: "57" },
    { name: "Can Tho", code: "CT" },
    { name: "Da Nang", code: "DN" },
    { name: "Dong Nai", code: "39" },
    { name: "Ha Noi", code: "HN" },
    { name: "Hai Phong", code: "HP" },
    { name: "Ho Chi Minh City", code: "SG" },
    { name: "Khanh Hoa", code: "34" },
    { name: "Lam Dong", code: "35" },
    { name: "Quang Ninh", code: "13" },
    { name: "Thai Nguyen", code: "20" },
    { name: "Thua Thien-Hue", code: "26" },
  ],
  KR: [
    { name: "Seoul", code: "11" },
    { name: "Busan", code: "26" },
    { name: "Daegu", code: "27" },
    { name: "Incheon", code: "28" },
    { name: "Gwangju", code: "29" },
    { name: "Daejeon", code: "30" },
    { name: "Ulsan", code: "31" },
    { name: "Sejong", code: "36" },
    { name: "Gyeonggi-do", code: "41" },
    { name: "Gangwon-do", code: "42" },
    { name: "Chungcheongbuk-do", code: "43" },
    { name: "Chungcheongnam-do", code: "44" },
    { name: "Jeollabuk-do", code: "45" },
    { name: "Jeollanam-do", code: "46" },
    { name: "Gyeongsangbuk-do", code: "47" },
    { name: "Gyeongsangnam-do", code: "48" },
    { name: "Jeju-do", code: "49" },
  ],
  IT: [
    { name: "Abruzzo", code: "65" },
    { name: "Basilicata", code: "77" },
    { name: "Calabria", code: "78" },
    { name: "Campania", code: "72" },
    { name: "Emilia-Romagna", code: "45" },
    { name: "Friuli Venezia Giulia", code: "36" },
    { name: "Lazio", code: "62" },
    { name: "Liguria", code: "42" },
    { name: "Lombardy", code: "25" },
    { name: "Marche", code: "57" },
    { name: "Molise", code: "67" },
    { name: "Piedmont", code: "21" },
    { name: "Puglia", code: "75" },
    { name: "Sardinia", code: "88" },
    { name: "Sicily", code: "82" },
    { name: "Trentino-Alto Adige", code: "32" },
    { name: "Tuscany", code: "52" },
    { name: "Umbria", code: "55" },
    { name: "Valle d'Aosta", code: "23" },
    { name: "Veneto", code: "34" },
  ],
  ES: [
    { name: "Andalusia", code: "AN" },
    { name: "Aragon", code: "AR" },
    { name: "Asturias", code: "AS" },
    { name: "Balearic Islands", code: "IB" },
    { name: "Basque Country", code: "PV" },
    { name: "Canary Islands", code: "CN" },
    { name: "Cantabria", code: "CB" },
    { name: "Castilla-La Mancha", code: "CM" },
    { name: "Castile and León", code: "CL" },
    { name: "Catalonia", code: "CT" },
    { name: "Ceuta", code: "CE" },
    { name: "Extremadura", code: "EX" },
    { name: "Galicia", code: "GA" },
    { name: "La Rioja", code: "RI" },
    { name: "Madrid", code: "MD" },
    { name: "Melilla", code: "ML" },
    { name: "Murcia", code: "MC" },
    { name: "Navarre", code: "NC" },
    { name: "Valencia", code: "VC" },
  ],
  NL: [
    { name: "Drenthe", code: "DR" },
    { name: "Flevoland", code: "FL" },
    { name: "Friesland", code: "FR" },
    { name: "Gelderland", code: "GE" },
    { name: "Groningen", code: "GR" },
    { name: "Limburg", code: "LI" },
    { name: "North Brabant", code: "NB" },
    { name: "North Holland", code: "NH" },
    { name: "Overijssel", code: "OV" },
    { name: "South Holland", code: "ZH" },
    { name: "Utrecht", code: "UT" },
    { name: "Zeeland", code: "ZE" },
  ],
  PL: [
    { name: "Greater Poland", code: "WP" },
    { name: "Kuyavian-Pomeranian", code: "KP" },
    { name: "Lesser Poland", code: "MA" },
    { name: "Łódź", code: "LD" },
    { name: "Lower Silesian", code: "DS" },
    { name: "Lublin", code: "LU" },
    { name: "Lubusz", code: "LB" },
    { name: "Masovian", code: "MZ" },
    { name: "Opole", code: "OP" },
    { name: "Podlaskie", code: "PD" },
    { name: "Pomeranian", code: "PM" },
    { name: "Silesian", code: "SL" },
    { name: "Subcarpathian", code: "PK" },
    { name: "Świętokrzyskie", code: "SK" },
    { name: "Warmian-Masurian", code: "WN" },
    { name: "West Pomeranian", code: "ZP" },
  ],
  SA: [
    { name: "Riyadh", code: "01" },
    { name: "Makkah", code: "02" },
    { name: "Madinah", code: "03" },
    { name: "Eastern Province", code: "04" },
    { name: "Asir", code: "14" },
    { name: "Qassim", code: "05" },
    { name: "Tabuk", code: "07" },
    { name: "Hail", code: "06" },
    { name: "Northern Borders", code: "08" },
    { name: "Jazan", code: "09" },
    { name: "Najran", code: "10" },
    { name: "Al Bahah", code: "11" },
    { name: "Al Jawf", code: "12" },
  ],
  EG: [
    { name: "Cairo", code: "C" },
    { name: "Alexandria", code: "ALX" },
    { name: "Giza", code: "GZ" },
    { name: "Qalyubia", code: "KB" },
    { name: "Port Said", code: "PTS" },
    { name: "Suez", code: "SUZ" },
    { name: "Luxor", code: "LX" },
    { name: "Aswan", code: "ASN" },
    { name: "Red Sea", code: "BA" },
    { name: "Beheira", code: "BH" },
    { name: "Dakahlia", code: "DK" },
    { name: "Gharbia", code: "GH" },
    { name: "Ismailia", code: "IS" },
    { name: "Kafr El Sheikh", code: "KFS" },
    { name: "Sharqia", code: "SHR" },
  ],
  TR: [
    { name: "Istanbul", code: "34" },
    { name: "Ankara", code: "06" },
    { name: "Izmir", code: "35" },
    { name: "Bursa", code: "16" },
    { name: "Antalya", code: "07" },
    { name: "Adana", code: "01" },
    { name: "Konya", code: "42" },
    { name: "Gaziantep", code: "27" },
    { name: "Kocaeli", code: "41" },
    { name: "Mersin", code: "33" },
    { name: "Diyarbakir", code: "21" },
    { name: "Kayseri", code: "38" },
    { name: "Eskisehir", code: "26" },
    { name: "Samsun", code: "55" },
    { name: "Trabzon", code: "61" },
  ],
  AR: [
    { name: "Buenos Aires", code: "B" },
    { name: "Buenos Aires City", code: "C" },
    { name: "Catamarca", code: "K" },
    { name: "Chaco", code: "H" },
    { name: "Chubut", code: "U" },
    { name: "Córdoba", code: "X" },
    { name: "Corrientes", code: "W" },
    { name: "Entre Ríos", code: "E" },
    { name: "Formosa", code: "P" },
    { name: "Jujuy", code: "Y" },
    { name: "La Pampa", code: "L" },
    { name: "La Rioja", code: "F" },
    { name: "Mendoza", code: "M" },
    { name: "Misiones", code: "N" },
    { name: "Neuquén", code: "Q" },
    { name: "Río Negro", code: "R" },
    { name: "Salta", code: "A" },
    { name: "San Juan", code: "J" },
    { name: "San Luis", code: "D" },
    { name: "Santa Cruz", code: "Z" },
    { name: "Santa Fe", code: "S" },
    { name: "Santiago del Estero", code: "G" },
    { name: "Tierra del Fuego", code: "V" },
    { name: "Tucumán", code: "T" },
  ],
  CL: [
    { name: "Arica y Parinacota", code: "AP" },
    { name: "Tarapacá", code: "TA" },
    { name: "Antofagasta", code: "AN" },
    { name: "Atacama", code: "AT" },
    { name: "Coquimbo", code: "CO" },
    { name: "Valparaíso", code: "VS" },
    { name: "Santiago Metropolitan", code: "RM" },
    { name: "O'Higgins", code: "LI" },
    { name: "Maule", code: "ML" },
    { name: "Ñuble", code: "NB" },
    { name: "Biobío", code: "BI" },
    { name: "Araucanía", code: "AR" },
    { name: "Los Ríos", code: "LR" },
    { name: "Los Lagos", code: "LL" },
    { name: "Aysén", code: "AI" },
    { name: "Magallanes", code: "MA" },
  ],
  CO: [
    { name: "Amazonas", code: "AMA" },
    { name: "Antioquia", code: "ANT" },
    { name: "Arauca", code: "ARA" },
    { name: "Atlántico", code: "ATL" },
    { name: "Bogotá", code: "DC" },
    { name: "Bolívar", code: "BOL" },
    { name: "Boyacá", code: "BOY" },
    { name: "Caldas", code: "CAL" },
    { name: "Caquetá", code: "CAQ" },
    { name: "Casanare", code: "CAS" },
    { name: "Cauca", code: "CAU" },
    { name: "Cesar", code: "CES" },
    { name: "Chocó", code: "CHO" },
    { name: "Córdoba", code: "COR" },
    { name: "Cundinamarca", code: "CUN" },
    { name: "Guainía", code: "GUA" },
    { name: "Guaviare", code: "GUV" },
    { name: "Huila", code: "HUI" },
    { name: "La Guajira", code: "LAG" },
    { name: "Magdalena", code: "MAG" },
    { name: "Meta", code: "MET" },
    { name: "Nariño", code: "NAR" },
    { name: "Norte de Santander", code: "NSA" },
    { name: "Putumayo", code: "PUT" },
    { name: "Quindío", code: "QUI" },
    { name: "Risaralda", code: "RIS" },
    { name: "San Andrés y Providencia", code: "SAP" },
    { name: "Santander", code: "SAN" },
    { name: "Sucre", code: "SUC" },
    { name: "Tolima", code: "TOL" },
    { name: "Valle del Cauca", code: "VAC" },
    { name: "Vaupés", code: "VAU" },
    { name: "Vichada", code: "VID" },
  ],
  PE: [
    { name: "Amazonas", code: "AMA" },
    { name: "Áncash", code: "ANC" },
    { name: "Apurímac", code: "APU" },
    { name: "Arequipa", code: "ARE" },
    { name: "Ayacucho", code: "AYA" },
    { name: "Cajamarca", code: "CAJ" },
    { name: "Callao", code: "CAL" },
    { name: "Cusco", code: "CUS" },
    { name: "Huancavelica", code: "HUV" },
    { name: "Huánuco", code: "HUC" },
    { name: "Ica", code: "ICA" },
    { name: "Junín", code: "JUN" },
    { name: "La Libertad", code: "LAL" },
    { name: "Lambayeque", code: "LAM" },
    { name: "Lima", code: "LIM" },
    { name: "Loreto", code: "LOR" },
    { name: "Madre de Dios", code: "MDD" },
    { name: "Moquegua", code: "MOQ" },
    { name: "Pasco", code: "PAS" },
    { name: "Piura", code: "PIU" },
    { name: "Puno", code: "PUN" },
    { name: "San Martín", code: "SAM" },
    { name: "Tacna", code: "TAC" },
    { name: "Tumbes", code: "TUM" },
    { name: "Ucayali", code: "UCA" },
  ],
  NZ: [
    { name: "Auckland", code: "AUK" },
    { name: "Bay of Plenty", code: "BOP" },
    { name: "Canterbury", code: "CAN" },
    { name: "Gisborne", code: "GIS" },
    { name: "Hawke's Bay", code: "HKB" },
    { name: "Manawatu-Wanganui", code: "MWT" },
    { name: "Marlborough", code: "MBH" },
    { name: "Nelson", code: "NSN" },
    { name: "Northland", code: "NTL" },
    { name: "Otago", code: "OTA" },
    { name: "Southland", code: "STL" },
    { name: "Taranaki", code: "TKI" },
    { name: "Tasman", code: "TAS" },
    { name: "Waikato", code: "WKO" },
    { name: "Wellington", code: "WGN" },
    { name: "West Coast", code: "WTC" },
  ],
  IE: [
    { name: "Carlow", code: "CW" },
    { name: "Cavan", code: "CN" },
    { name: "Clare", code: "CE" },
    { name: "Cork", code: "CO" },
    { name: "Donegal", code: "DL" },
    { name: "Dublin", code: "D" },
    { name: "Galway", code: "G" },
    { name: "Kerry", code: "KY" },
    { name: "Kildare", code: "KE" },
    { name: "Kilkenny", code: "KK" },
    { name: "Laois", code: "LS" },
    { name: "Leitrim", code: "LM" },
    { name: "Limerick", code: "LK" },
    { name: "Longford", code: "LD" },
    { name: "Louth", code: "LH" },
    { name: "Mayo", code: "MO" },
    { name: "Meath", code: "MH" },
    { name: "Monaghan", code: "MN" },
    { name: "Offaly", code: "OY" },
    { name: "Roscommon", code: "RN" },
    { name: "Sligo", code: "SO" },
    { name: "Tipperary", code: "TA" },
    { name: "Waterford", code: "WD" },
    { name: "Westmeath", code: "WH" },
    { name: "Wexford", code: "WX" },
    { name: "Wicklow", code: "WW" },
  ],
  CH: [
    { name: "Aargau", code: "AG" },
    { name: "Appenzell Ausserrhoden", code: "AR" },
    { name: "Appenzell Innerrhoden", code: "AI" },
    { name: "Basel-Landschaft", code: "BL" },
    { name: "Basel-Stadt", code: "BS" },
    { name: "Bern", code: "BE" },
    { name: "Fribourg", code: "FR" },
    { name: "Geneva", code: "GE" },
    { name: "Glarus", code: "GL" },
    { name: "Graubünden", code: "GR" },
    { name: "Jura", code: "JU" },
    { name: "Lucerne", code: "LU" },
    { name: "Neuchâtel", code: "NE" },
    { name: "Nidwalden", code: "NW" },
    { name: "Obwalden", code: "OW" },
    { name: "Schaffhausen", code: "SH" },
    { name: "Schwyz", code: "SZ" },
    { name: "Solothurn", code: "SO" },
    { name: "St. Gallen", code: "SG" },
    { name: "Thurgau", code: "TG" },
    { name: "Ticino", code: "TI" },
    { name: "Uri", code: "UR" },
    { name: "Valais", code: "VS" },
    { name: "Vaud", code: "VD" },
    { name: "Zug", code: "ZG" },
    { name: "Zürich", code: "ZH" },
  ],
  AT: [
    { name: "Burgenland", code: "1" },
    { name: "Carinthia", code: "2" },
    { name: "Lower Austria", code: "3" },
    { name: "Upper Austria", code: "4" },
    { name: "Salzburg", code: "5" },
    { name: "Styria", code: "6" },
    { name: "Tyrol", code: "7" },
    { name: "Vorarlberg", code: "8" },
    { name: "Vienna", code: "9" },
  ],
  SE: [
    { name: "Blekinge", code: "K" },
    { name: "Dalarna", code: "W" },
    { name: "Gävleborg", code: "X" },
    { name: "Gotland", code: "I" },
    { name: "Halland", code: "N" },
    { name: "Jämtland", code: "Z" },
    { name: "Jönköping", code: "F" },
    { name: "Kalmar", code: "H" },
    { name: "Kronoberg", code: "G" },
    { name: "Norrbotten", code: "BD" },
    { name: "Örebro", code: "T" },
    { name: "Östergötland", code: "E" },
    { name: "Skåne", code: "M" },
    { name: "Södermanland", code: "D" },
    { name: "Stockholm", code: "AB" },
    { name: "Uppsala", code: "C" },
    { name: "Värmland", code: "S" },
    { name: "Västerbotten", code: "AC" },
    { name: "Västernorrland", code: "Y" },
    { name: "Västmanland", code: "U" },
    { name: "Västra Götaland", code: "O" },
  ],
  NO: [
    { name: "Agder", code: "42" },
    { name: "Innlandet", code: "34" },
    { name: "Møre og Romsdal", code: "15" },
    { name: "Nordland", code: "18" },
    { name: "Oslo", code: "03" },
    { name: "Rogaland", code: "11" },
    { name: "Troms og Finnmark", code: "54" },
    { name: "Trøndelag", code: "50" },
    { name: "Vestfold og Telemark", code: "38" },
    { name: "Vestland", code: "46" },
    { name: "Viken", code: "30" },
  ],
  DK: [
    { name: "Capital Region", code: "84" },
    { name: "Central Denmark", code: "82" },
    { name: "North Denmark", code: "81" },
    { name: "Region Zealand", code: "85" },
    { name: "Southern Denmark", code: "83" },
  ],
  FI: [
    { name: "Åland Islands", code: "01" },
    { name: "Central Finland", code: "08" },
    { name: "Central Ostrobothnia", code: "07" },
    { name: "Kainuu", code: "05" },
    { name: "Kanta-Häme", code: "06" },
    { name: "Kymenlaakso", code: "09" },
    { name: "Lapland", code: "10" },
    { name: "North Karelia", code: "13" },
    { name: "North Ostrobothnia", code: "14" },
    { name: "North Savo", code: "15" },
    { name: "Ostrobothnia", code: "12" },
    { name: "Päijät-Häme", code: "16" },
    { name: "Pirkanmaa", code: "11" },
    { name: "Satakunta", code: "17" },
    { name: "South Karelia", code: "02" },
    { name: "South Ostrobothnia", code: "03" },
    { name: "South Savo", code: "04" },
    { name: "Southwest Finland", code: "19" },
    { name: "Uusimaa", code: "18" },
  ],
  GR: [
    { name: "Attica", code: "I" },
    { name: "Central Greece", code: "H" },
    { name: "Central Macedonia", code: "B" },
    { name: "Crete", code: "M" },
    { name: "Eastern Macedonia and Thrace", code: "A" },
    { name: "Epirus", code: "D" },
    { name: "Ionian Islands", code: "F" },
    { name: "North Aegean", code: "K" },
    { name: "Peloponnese", code: "J" },
    { name: "South Aegean", code: "L" },
    { name: "Thessaly", code: "E" },
    { name: "Western Greece", code: "G" },
    { name: "Western Macedonia", code: "C" },
  ],
  PT: [
    { name: "Açores", code: "20" },
    { name: "Aveiro", code: "01" },
    { name: "Beja", code: "02" },
    { name: "Braga", code: "03" },
    { name: "Bragança", code: "04" },
    { name: "Castelo Branco", code: "05" },
    { name: "Coimbra", code: "06" },
    { name: "Évora", code: "07" },
    { name: "Faro", code: "08" },
    { name: "Guarda", code: "09" },
    { name: "Leiria", code: "10" },
    { name: "Lisboa", code: "11" },
    { name: "Madeira", code: "30" },
    { name: "Portalegre", code: "12" },
    { name: "Porto", code: "13" },
    { name: "Santarém", code: "14" },
    { name: "Setúbal", code: "15" },
    { name: "Viana do Castelo", code: "16" },
    { name: "Vila Real", code: "17" },
    { name: "Viseu", code: "18" },
  ],
  IL: [
    { name: "Central District", code: "M" },
    { name: "Haifa District", code: "HA" },
    { name: "Jerusalem District", code: "JM" },
    { name: "Northern District", code: "Z" },
    { name: "Southern District", code: "D" },
    { name: "Tel Aviv District", code: "TA" },
  ],
  KE: [
    { name: "Central", code: "01" },
    { name: "Coast", code: "02" },
    { name: "Eastern", code: "03" },
    { name: "Nairobi", code: "05" },
    { name: "North Eastern", code: "06" },
    { name: "Nyanza", code: "07" },
    { name: "Rift Valley", code: "08" },
    { name: "Western", code: "09" },
  ],
  GH: [
    { name: "Ahafo", code: "AF" },
    { name: "Ashanti", code: "AH" },
    { name: "Bono", code: "BO" },
    { name: "Bono East", code: "BE" },
    { name: "Central", code: "CP" },
    { name: "Eastern", code: "EP" },
    { name: "Greater Accra", code: "AA" },
    { name: "North East", code: "NE" },
    { name: "Northern", code: "NP" },
    { name: "Oti", code: "OT" },
    { name: "Savannah", code: "SV" },
    { name: "Upper East", code: "UE" },
    { name: "Upper West", code: "UW" },
    { name: "Volta", code: "TV" },
    { name: "Western", code: "WP" },
    { name: "Western North", code: "WN" },
  ],
  TZ: [
    { name: "Arusha", code: "01" },
    { name: "Dar es Salaam", code: "02" },
    { name: "Dodoma", code: "03" },
    { name: "Geita", code: "27" },
    { name: "Iringa", code: "04" },
    { name: "Kagera", code: "05" },
    { name: "Katavi", code: "28" },
    { name: "Kigoma", code: "08" },
    { name: "Kilimanjaro", code: "09" },
    { name: "Lindi", code: "12" },
    { name: "Manyara", code: "26" },
    { name: "Mara", code: "13" },
    { name: "Mbeya", code: "14" },
    { name: "Morogoro", code: "16" },
    { name: "Mtwara", code: "17" },
    { name: "Mwanza", code: "18" },
    { name: "Njombe", code: "29" },
    { name: "Pwani", code: "19" },
    { name: "Rukwa", code: "20" },
    { name: "Ruvuma", code: "21" },
    { name: "Shinyanga", code: "22" },
    { name: "Simiyu", code: "30" },
    { name: "Singida", code: "23" },
    { name: "Songwe", code: "31" },
    { name: "Tabora", code: "24" },
    { name: "Tanga", code: "25" },
    { name: "Zanzibar", code: "07" },
  ],
  UG: [
    { name: "Central", code: "C" },
    { name: "Eastern", code: "E" },
    { name: "Northern", code: "N" },
    { name: "Western", code: "W" },
  ],
  ET: [
    { name: "Addis Ababa", code: "AA" },
    { name: "Afar", code: "AF" },
    { name: "Amhara", code: "AM" },
    { name: "Benishangul-Gumuz", code: "BE" },
    { name: "Dire Dawa", code: "DD" },
    { name: "Gambela", code: "GA" },
    { name: "Harari", code: "HA" },
    { name: "Oromia", code: "OR" },
    { name: "Sidama", code: "SI" },
    { name: "Somali", code: "SO" },
    { name: "Southern Nations", code: "SN" },
    { name: "Tigray", code: "TI" },
  ],
  MA: [
    { name: "Béni Mellal-Khénifra", code: "05" },
    { name: "Casablanca-Settat", code: "06" },
    { name: "Drâa-Tafilalet", code: "08" },
    { name: "Fès-Meknès", code: "03" },
    { name: "Guelmim-Oued Noun", code: "10" },
    { name: "Laâyoune-Sakia El Hamra", code: "11" },
    { name: "Marrakech-Safi", code: "07" },
    { name: "Oriental", code: "02" },
    { name: "Rabat-Salé-Kénitra", code: "04" },
    { name: "Souss-Massa", code: "09" },
    { name: "Tanger-Tétouan-Al Hoceïma", code: "01" },
  ],
  LK: [
    { name: "Central", code: "2" },
    { name: "Eastern", code: "5" },
    { name: "North Central", code: "7" },
    { name: "Northern", code: "4" },
    { name: "North Western", code: "6" },
    { name: "Sabaragamuwa", code: "9" },
    { name: "Southern", code: "3" },
    { name: "Uva", code: "8" },
    { name: "Western", code: "1" },
  ],
  NP: [
    { name: "Province No. 1", code: "P1" },
    { name: "Madhesh Province", code: "P2" },
    { name: "Bagmati Province", code: "P3" },
    { name: "Gandaki Province", code: "P4" },
    { name: "Lumbini Province", code: "P5" },
    { name: "Karnali Province", code: "P6" },
    { name: "Sudurpashchim Province", code: "P7" },
  ],
};
