const colors = {
  light: {
    text: "#1a1033",
    tint: "#8A2BE2",
    background: "#f5f4fb",
    foreground: "#1a1033",
    card: "#ffffff",
    cardForeground: "#1a1033",
    primary: "#8A2BE2",
    primaryForeground: "#ffffff",
    secondary: "#f0ebfd",
    secondaryForeground: "#4a2080",
    muted: "#ede9f7",
    mutedForeground: "#7a6e99",
    accent: "#FF2FBF",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e0d9f5",
    input: "#e0d9f5",
    gradientStart: "#8A2BE2",
    gradientEnd: "#FF2FBF",
    goldStar: "#F5C518",
    success: "#22c55e",
  },
  dark: {
    text: "#f0ebfd",
    tint: "#a855f7",
    background: "#0D0A1E",
    foreground: "#f0ebfd",
    card: "#1a1033",
    cardForeground: "#f0ebfd",
    primary: "#a855f7",
    primaryForeground: "#0D0A1E",
    secondary: "#1e1540",
    secondaryForeground: "#c4aff7",
    muted: "#1a1033",
    mutedForeground: "#7a6e99",
    accent: "#FF2FBF",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#2a1f4a",
    input: "#2a1f4a",
    gradientStart: "#8A2BE2",
    gradientEnd: "#FF2FBF",
    goldStar: "#F5C518",
    success: "#22c55e",
  },
  radius: 12,
};

export default colors;
