// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cert-fonts/AbrilFatface.tsx": () => import("../components/mockups/cert-fonts/AbrilFatface.tsx"),
  "./components/mockups/cert-fonts/Almendra.tsx": () => import("../components/mockups/cert-fonts/Almendra.tsx"),
  "./components/mockups/cert-fonts/BodoniModa.tsx": () => import("../components/mockups/cert-fonts/BodoniModa.tsx"),
  "./components/mockups/cert-fonts/CinzelAlphabet.tsx": () => import("../components/mockups/cert-fonts/CinzelAlphabet.tsx"),
  "./components/mockups/cert-fonts/CinzelDecorative.tsx": () => import("../components/mockups/cert-fonts/CinzelDecorative.tsx"),
  "./components/mockups/cert-fonts/CormorantSC.tsx": () => import("../components/mockups/cert-fonts/CormorantSC.tsx"),
  "./components/mockups/cert-fonts/CormorantUpright.tsx": () => import("../components/mockups/cert-fonts/CormorantUpright.tsx"),
  "./components/mockups/cert-fonts/Fraunces.tsx": () => import("../components/mockups/cert-fonts/Fraunces.tsx"),
  "./components/mockups/cert-fonts/LibreCaslon.tsx": () => import("../components/mockups/cert-fonts/LibreCaslon.tsx"),
  "./components/mockups/cert-fonts/MarcellusSC.tsx": () => import("../components/mockups/cert-fonts/MarcellusSC.tsx"),
  "./components/mockups/cert-fonts/Rufina.tsx": () => import("../components/mockups/cert-fonts/Rufina.tsx"),
  "./components/mockups/cert-fonts/YesevaOne.tsx": () => import("../components/mockups/cert-fonts/YesevaOne.tsx")
};
